name: MediaFlow

options:
  bundleIdPrefix: com.mediaflow
  deploymentTarget:
    macOS: "14.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: false
  groupSortPosition: top

settings:
  base:
    SWIFT_VERSION: "5.9"
    SWIFT_STRICT_CONCURRENCY: complete
    MACOSX_DEPLOYMENT_TARGET: "14.0"
    PRODUCT_NAME: MediaFlow
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"
    GENERATE_INFOPLIST_FILE: false
    INFOPLIST_FILE: MediaFlow/Info.plist
    CODE_SIGN_ENTITLEMENTS: MediaFlow/MediaFlow.entitlements
    CODE_SIGN_STYLE: Automatic
    ENABLE_HARDENED_RUNTIME: true
    COMBINE_HIDPI_IMAGES: true
    ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor

targets:
  MediaFlow:
    type: application
    platform: macOS
    deploymentTarget: "14.0"

    sources:
      - path: MediaFlow
        excludes:
          - "**/.DS_Store"
          - "Info.plist"

    resources:
      - path: MediaFlow/Resources/Assets.xcassets

    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.mediaflow.app
        SWIFT_VERSION: "5.9"
        SWIFT_STRICT_CONCURRENCY: complete
        CODE_SIGN_ENTITLEMENTS: MediaFlow/MediaFlow.entitlements
        INFOPLIST_FILE: MediaFlow/Info.plist
        LD_RUNPATH_SEARCH_PATHS:
          - $(inherited)
          - "@executable_path/../Frameworks"
      configs:
        Debug:
          SWIFT_OPTIMIZATION_LEVEL: "-Onone"
          SWIFT_ACTIVE_COMPILATION_CONDITIONS: DEBUG
          DEBUG_INFORMATION_FORMAT: "dwarf-with-dsym"
          MTL_ENABLE_DEBUG_INFO: "INCLUDE_SOURCE"
        Release:
          SWIFT_OPTIMIZATION_LEVEL: "-O"
          SWIFT_COMPILATION_MODE: wholemodule
          DEBUG_INFORMATION_FORMAT: "dwarf-with-dsym"
          COPY_PHASE_STRIP: true
          ENABLE_NS_ASSERTIONS: false

    entitlements:
      path: MediaFlow/MediaFlow.entitlements
      properties:
        com.apple.security.app-sandbox: false
        com.apple.security.network.client: true
        com.apple.security.files.user-selected.read-write: true

schemes:
  MediaFlow:
    build:
      targets:
        MediaFlow: all
    run:
      config: Debug
      commandLineArguments:
        "-com.apple.CoreData.ConcurrencyDebug 1": false
    test:
      config: Debug
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
